export App from './App/App';
export Home from './Home/Home';
export Login from './Login/Login';
export Register from './Register/Register';
export Dashboard from './Dashboard/Dashboard';
export HomeDashboard from './HomeDashboard/HomeDashboard';
export DatatableClient from './Client/DatatableClient';
export ShowClient from './Client/ShowClient';
export Map from './Map/Map';
